name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  pepengu/gamewise_api:latest
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/backend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Run Tests
        working-directory: backend
        run: |
          python manage.py test

  run-linters:
    name: Run linters

    runs-on: ubuntu-latest

    container:
      image:  pepengu/gamewise_api:latest
      volumes:
        - ./backend:/backend
      options: --user root

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: backend
        run: |
          pip install black

      - name: Run linters
        working-directory: backend
        run: |
          python -m black . --check --diff --color
