name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    container:
      image: pepengu/gamewise_web:latest
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/frontend

    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: frontend
        run: |
             npm run build

      - name: Run Tests
        working-directory: frontend
        run: |
             npm test
